### PR TITLE
Fix Windows reinstall/uninstall issue

### LINKED ISSUE #190: Reinstalling or Uninstalling Windows extensions fails
Reinstalling or uninstalling an extension in Windows does not work currently.

This is because when DLL is loaded in Windows, we cannot unload it from PHP in order to free Windows' lock on the file. If you attempt to overwrite or uninstall the DLL in Windows, you will get an unhelpful/cryptic error like:

> ```
> PHP Warning:  copy(C:\tools\php\ext\php_example_pie_extension.dll): Failed to
> open stream: Resource temporarily unavailable in src\Installing\WindowsInstall.php on line 127
> ```

(this specific error is trying to re-install an ext that is already installed)

After some searching, it seems this is because the DLL is loaded and therefore cannot be "written" whilst loaded. One potential solution here is to relaunch PHP without the extension loaded. I believe Composer has a mechanism to reload without `xdebug` (for performance) so it may be possible to leverage that.

### PR DESCRIPTION
**Pull request by asgrim**
Fixes #190

### CODE REVIEW

File: src/File/WindowsDelete.php [hunk 1]
```diff
@@ -0,0 +1,47 @@
...
+
+/** @internal This is not public API for PIE, so should not be depended upon unless you accept the risk of BC breaks */
+final class WindowsDelete
+{
+    /**
+     * Windows will hold a lock on the DLL, so we can't actually replace or
+     * delete the extension. However, Windows lets us move it out the way,
+     * so move it to the temp directory. It can then be cleaned up later.
+     */
+    public static function usingMoveToTemp(string $filename): void
```
Comment (asgrim) [inline src/File/WindowsDelete.php:23]: Note: not ideal, as it leaves a dangling temp file, but not sure a way around the lock on the file. Any suggestions to improve this are welcomed!
