### PR TITLE
462: fix intermittent failure to look up packages

### LINKED ISSUE #462: Occasional 'module not found' breaks build, but passes on retry
It seems like for some reason modules can not get found. The one time its the one module, the other time another module. 

Thereafter retrying the build then results in a successful run again.

The output on the reason why the module was not found is not shown, is there a more verbose output mode so I can provide more additional context?

## Missing imagick
Image

## Missing redis
Image

### PR DESCRIPTION
**Pull request by asgrim**
Fixes #462

### CODE REVIEW

File: src/Installing/InstallForPhpProject/FindMatchingPackages.php [hunk 1]
```diff
@@ -41,7 +41,7 @@ public function for(Composer $pieComposer, string $searchTerm): array
                 static function (array $match) use ($pieComposer, $extensionName): bool {
                     $package = $pieComposer->getRepositoryManager()->findPackage($match['name'], '*');
 
-                    if (! $package instanceof CompletePackage) {
+                    if (! $package instanceof CompletePackageInterface) {
```
Comment (asgrim) [inline src/Installing/InstallForPhpProject/FindMatchingPackages.php:44]: This is the root cause; sometimes (for whatever reason), Composer will return a `CompleteAliasPackage` instead of a `CompletePackage`, which we were discarding. The correct check is now in place, and I can no longer reproduce the reported issue 👍
