### PR TITLE
Fixing INI permissions issues

### LINKED ISSUE #197: Permission denied - missing a sudo in OndrejPhpenmod
```
Trying to enable extension using OndrejPhpenmod
PHP Warning:  touch(): Unable to create file /etc/php/8.3/mods-available/mongodb.ini because Permission denied in /home/james/workspace/phpf/pie/src/Installing/Ini/OndrejPhpenmod.php on line 142
```

### PR DESCRIPTION
**Pull request by asgrim**
Fixes #197

### CODE REVIEW

File: src/File/SudoFilePut.php [hunk 1]
```diff
@@ -6,61 +6,64 @@
...
+        self::writeWithSudo($filename, $content);
     }
 
-    private static function attemptToMakeFileEditable(string $filename): bool
+    private static function writeWithSudo(string $filename, string $content): void
     {
-        if (! Sudo::exists()) {
-            return false;
-        }
+        $tempFilename = sys_get_temp_dir() . DIRECTORY_SEPARATOR . 'pie_tmp_' . sha1($content);
```
Comment (TimWolla) [inline src/File/SudoFilePut.php:50]: Use [`tempnam`](https://www.php.net/manual/en/function.tempnam.php). This will take care of securely locking down the permissions when creating the file.

Comment (asgrim) [reply src/File/SudoFilePut.php]: Thanks! Good catch
